import { View, Text, ScrollView, StyleSheet } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import Header from "../../components/Header";

const INTRO_PARAGRAPHS = [
  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
  "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://doggos-heaven-app-frontend.vercel.app/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').",
  "The Platform is owned by Doggos Heaven Pvt. Ltd., a company incorporated under the Companies Act, 1956 with its registered office at Block J, VATIKA INDIA NEXT, Plot 11, near Vatika V'lante, Sector 83, Gurugram, Haryana 122004, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').",
  "Your use of the Platform and services and tools are governed by the following terms and conditions (\"Terms of Use\") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.",
  "For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.",
];

const SECTIONS = [
  {
    icon: "alert-circle-outline",
    title: "Agreement to Terms",
    content: "ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.",
  },
  {
    icon: "document-text-outline",
    title: "Terms of Use",
    bullets: [
      "7.1 To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
      "7.2 Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
      "7.3 Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
      "7.4 The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents include and are not limited to the design, layout, look and graphics.",
    ],
  },
  {
    icon: "paw-outline",
    title: "Ethical Breeding Practices",
    content: "We are committed to ethical and humane breeding practices. We do not engage in or support any form of abusive breeding. All pets available through our platform are sourced from responsible breeders who adhere to the highest standards of animal welfare.",
  },
  {
    icon: "heart-outline",
    title: "Pet Adoption & Community",
    content: "The procurement and adoption of pets through our platform are facilitated exclusively via our dedicated pet community. This community is built on trust, transparency, and a shared commitment to the well-being of animals. We ensure that all pets are placed in loving and suitable homes.",
  },
];

export default function TermsAndConditionsScreen() {
  return (
    <View style={styles.container}>
      <Header title="Terms & Conditions" showBack />
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>

        {/* Header Card */}
        <View style={styles.headerCard}>
          <Ionicons name="reader" size={36} color="#A8D96C" />
          <Text style={styles.headerTitle}>Terms & Conditions</Text>
          <Text style={styles.headerSub}>Last Updated: 26-03-2026</Text>
          <Text style={styles.headerDesc}>
            Please read these terms carefully before using the Doggos Heaven platform or services.
          </Text>
        </View>

        {/* Intro Paragraphs */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <View style={styles.iconBox}>
              <Ionicons name="information-circle-outline" size={20} color="#0B3D2E" />
            </View>
            <Text style={styles.cardTitle}>Overview</Text>
          </View>
          {INTRO_PARAGRAPHS.map((para, i) => (
            <Text key={i} style={[styles.cardContent, i < INTRO_PARAGRAPHS.length - 1 && styles.paraSpacing]}>
              {para}
            </Text>
          ))}
        </View>

        {/* Sections */}
        {SECTIONS.map((section, i) => (
          <View key={i} style={styles.card}>
            <View style={styles.cardHeader}>
              <View style={styles.iconBox}>
                <Ionicons name={section.icon} size={20} color="#0B3D2E" />
              </View>
              <Text style={styles.cardTitle}>{section.title}</Text>
            </View>
            {section.content && (
              <Text style={styles.cardContent}>{section.content}</Text>
            )}
            {section.bullets?.map((item, j) => (
              <View key={j} style={styles.bulletRow}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.bulletText}>{item}</Text>
              </View>
            ))}
          </View>
        ))}

        {/* Footer Note */}
        <View style={styles.footerCard}>
          <Ionicons name="refresh-outline" size={20} color="#A8D96C" style={{ marginBottom: 8 }} />
          <Text style={styles.footerText}>
            These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </Text>
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F0F7F0" },
  scroll: { padding: 16, paddingBottom: 40 },

  headerCard: {
    backgroundColor: "#0B3D2E", borderRadius: 20, padding: 24,
    alignItems: "center", marginBottom: 16, elevation: 3,
  },
  headerTitle: { fontSize: 20, fontFamily: "Poppins_700Bold", color: "#fff", marginTop: 10, marginBottom: 4 },
  headerSub: { fontSize: 11, fontFamily: "Inter_400Regular", color: "#A8D96C", marginBottom: 12 },
  headerDesc: { fontSize: 13, fontFamily: "Inter_400Regular", color: "#aaa", textAlign: "center", lineHeight: 20 },

  card: {
    backgroundColor: "#fff", borderRadius: 14, padding: 16,
    marginBottom: 10, elevation: 2,
    borderWidth: 1, borderColor: "#D4EDD4",
  },
  cardHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  iconBox: {
    width: 36, height: 36, borderRadius: 10,
    backgroundColor: "#E8F5E8",
    justifyContent: "center", alignItems: "center",
  },
  cardTitle: { fontSize: 14, fontFamily: "Poppins_700Bold", color: "#0B3D2E", flex: 1 },
  cardContent: { fontSize: 13, fontFamily: "Inter_400Regular", color: "#555", lineHeight: 20 },
  paraSpacing: { marginBottom: 10 },

  bulletRow: { flexDirection: "row", gap: 8, marginBottom: 10, paddingRight: 4 },
  bullet: { fontSize: 13, color: "#3E7B27", marginTop: 1 },
  bulletText: { fontSize: 13, fontFamily: "Inter_400Regular", color: "#555", lineHeight: 20, flex: 1 },

  footerCard: {
    backgroundColor: "#1A5C3A", borderRadius: 16, padding: 18,
    alignItems: "center", marginTop: 6,
  },
  footerText: { fontSize: 12, fontFamily: "Inter_400Regular", color: "#A8D96C", textAlign: "center", lineHeight: 18 },
});
